### PR TITLE
Fix array schema deserialization

### LINKED ISSUE #584: Fix issue in ArraySchema when items is an Object
When this spec is parse, parser doesn't deserialize the items.

```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test

paths:
  /mixed-array:
    get:
      responses:
        '200':
          description: An array containing strings and/or integers
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
```

### PR DESCRIPTION
**Pull request by gracekarina**
Fixes #584 came up while developing https://github.com/swagger-api/swagger-inflector/issues/215

### CODE REVIEW

File: modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java [hunk 1]
```diff
@@ -1817,10 +1817,16 @@ public Schema getSchema(ObjectNode node, String location, ParseResult result){
             schema = oneOfList;
         } else if(itemsNode != null) {
             ArraySchema items = new ArraySchema();
-            for(JsonNode n : itemsNode) {
-                if(n.isValueNode()) {
-                    items.setItems(getSchema(itemsNode, location, result));
+            if (itemsNode.getNodeType().equals(JsonNodeType.OBJECT)){
+                items.setItems(getSchema(itemsNode, location, result));
+            }else if (itemsNode.getNodeType().equals(JsonNodeType.ARRAY)){
```
Comment (frantuma) [inline modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java]: which case is this handling? should it be perhaps a recursive call instead?

File: modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java [hunk 2]
```diff
@@ -165,8 +165,11 @@ public Schema resolveSchema(Schema schema) {
 
         if(schema instanceof ArraySchema) {
             ArraySchema arrayModel = (ArraySchema) schema;
-            if(arrayModel.getItems().get$ref() != null) {
-                arrayModel.setItems(resolveSchema(arrayModel.getItems()));
+            if(arrayModel.getItems() != null){
+                arrayModel.setItems(arrayModel.getItems());
+                if(arrayModel.getItems().get$ref() != null) {
+                    arrayModel.setItems(resolveSchema(arrayModel.getItems()));
+                }
```
Comment (frantuma) [inline modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java]: maybe use if/else..
```
if(arrayModel.getItems().get$ref() != null) {
  arrayModel.setItems(resolveSchema(arrayModel.getItems()));
} else {
  arrayModel.setItems(arrayModel.getItems());
}
```

File: modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java (hunk 1 above)
Comment (gracekarina) [reply modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java]: hi I don't understand the question, getSchema() is a recursive call
